### ISSUE TITLE
This equation doesn't get balanced

### ISSUE THREAD

**Issue by ss3387** [richpsharp/chemical_equation_balancer#1]
Ca(OH)2 + H2SO4 = CaSO4 + H2O

Balanced equation: 
Traceback (most recent call last):
  File "/Users/sridh/Documents/hello.py", line 86, in <module>
    main(input())
  File "/Users/sridh/Documents/hello.py", line 76, in main
    for c, molecule in zip(constants.x, left_molecule_str_list)])}""")
TypeError: 'NoneType' object is not iterable

**Comment by richpsharp** [comment]
thanks @ss3387, I fixed this issue. I wasn't accounting for nested molecules like Ca(OH)2 but instead manually expanding them like CaO2H2. But the script now handles both.
